# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05a64ec2dafacadd71255c56790d9c2726f6e219e3e9e92335b7ee0bc3f0c9862d12d5f37ebf650f335f4094165f0d897dd5c373c5a3f5f3ce80163d940ca3c2

test:
  secret_key_base: 4fb67d84cca1da42cdaac34f6be4cdd8a091d3e35e291e84e1be8267c40ab0be04c051f72cef02596917e4ca568f0ed380a9c4c207bc59fc02885ef690048d65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
